### ISSUE TITLE
render_dict_populate_actions AssertionError

### ISSUE THREAD

**Issue by tudang** [P4-vSwitch/ovs#6]
I try to run the following program on P4-vSwitch [main.p4.txt](https://github.com/P4-vSwitch/ovs/files/541545/main.p4.txt). Although the program successfully ran on Bmv2, it failed to run on P4-vSwitch. Is this a bug/limitation of P4-vSwitch?

```
WARNING: No error rule is defined for exclusive state 'pragma'
WARNING: Token 'PPHASH' defined, but not used
WARNING: There is 1 unused token
parsing successful
semantic checking successful
Header type standard_metadata_t not byte-aligned, adding padding
Generating files in directory /home/vagrant/dpl-benchmark/pisces/include/p4/src/temp
total phv length (in bytes): 172
<class 'p4_hlir.hlir.p4_expressions.p4_expression'>
Traceback (most recent call last):
  File "/usr/local/bin/p4c-behavioral", line 9, in <module>
    load_entry_point('p4c-behavioral==0.9.4', 'console_scripts', 'p4c-behavioral')()
  File "/usr/local/lib/python2.7/dist-packages/p4c_behavioral-0.9.4-py2.7.egg/p4c_bm/shell.py", line 133, in main
    dump_yaml = args.dump_yaml)
  File "/usr/local/lib/python2.7/dist-packages/p4c_behavioral-0.9.4-py2.7.egg/p4c_bm/smart.py", line 1237, in render_dict_create
    render_dict_populate_actions(render_dict, hlir)
  File "/usr/local/lib/python2.7/dist-packages/p4c_behavioral-0.9.4-py2.7.egg/p4c_bm/smart.py", line 587, in render_dict_populate_actions
    assert(False)
AssertionError
```

**Comment by mshahbaz** [comment]
Hi Tu, it seems like you are passing an expression "header_0.filed_0+1" to the modify_field action. This isn't supported in the v1.0 spec that p4c-behvioral is using. Instead, you should use the add_to_field or the add action for incrementing the value of the field.

I just replaced modify_field(header_0.field_0, header_0.field_0 + 1); with add_to_field(header_0.field_0, 1); and it compiled correctly.

**Comment by tudang** [comment]
Oh, you're right. I had thought that is supported in P4 v1.0.
